package com.adv.soft.models;

import lombok.Getter;


public enum Industry {
AC("Accounting"),
AVL("Airlines/Aviation"),
ADP("Alternative Dispute Resolution"),
AM("Alternative Medicine"),
AN("Animation"),
AP("Apparel & Fashion"),
AR("Architecture & Planning"),
ACR("Arts and Crafts"),
ATM("Automotive "),
AV("Aviation & Aerospace"),
BA("Banking"),
BI("Biotechnology"),
BM("BroadcastMedia"),
BLM("BuildingMaterials"),
BSE("BusinessSuppliesandEquipment"),
CM("CapitalMarkets"),
CH("Chemicals"),
CSO("Civic&SocialOrganization"),
CE("CivilEngineering"),
CRE("CommercialRealEstate"),
CNS("Computer&NetworkSecurity"),
CG("ComputerGames"),
CHA("ComputerHardware"),
CN("ComputerNetworking"),
CS("ComputerSoftware"),
CO("Construction"),
CEL("ConsumerElectronics"),
CGO("ConsumerGoods"),
CSE("ConsumerServices"),
COS("Cosmetics"),
DS("Defense&Space"),
DE("Design"),
EM("EducationManagement"),
EL("E-Learning"),
EE("Electrical/ElectronicManufacturing"),
EN("Entertainment"),
ENV("EnvironmentalServices"),
EVS("EventsServices"),
EX("ExecutiveOffice"),
FAS("FacilitiesServices"),
FAR("Farming"),
FS("FinancialServices"),
FA("FineArt"),
FI("Fishery"),
FB("Food&Beverages"),
FP("FoodProduction"),
FR("Fund-Raising"),
FU("Furniture"),
GAC("Gambling&Casinos"),
GCC("Glass,Ceramics&Concrete"),
GA("GovernmentAdministration"),
GR("GovernmentRelations"),
GD("GraphicDesign"),
HW("Health,WellnessandFitness"),
HE("HigherEducation"),
HH("Hospital&HealthCare"),
HO("Hospitality"),
HR("HumanResources"),
IE("ImportandExport"),
IFS("Individual&FamilyServices"),
IAU("IndustrialAutomation"),
IS("InformationServices"),
IT("InformationTechnologyandServices"),
INS("Insurance"),
IA("InternationalAffairs"),
ITD("InternationalTradeandDevelopment"),
IN("Internet"),
IB("InvestmentBanking"),
IM("InvestmentManagement"),
JU("Judiciary"),
LE("LawEnforcement"),
LP("LawPractice"),
LES("LegalServices"),
LO("LegislativeOffice"),
LTT("Leisure,Travel&Tourism"),
LI("Libraries"),
LS("LogisticsandSupplyChain"),
LG("LuxuryGoods&Jewelry"),
MA("Machinery"),
MC("ManagementConsulting"),
MAR("Maritime"),
MR("MarketResearch"),
MAA("MarketingandAdvertising"),
MIN("MechanicalorIndustrialEngineering"),
MPO("MediaProduction"),
MD("MedicalDevices"),
MEP("MedicalPractice"),
MH("MentalHealthCare"),
MI("Military"),
MM("Mining&Metals"),
MP("MotionPicturesandFilm"),
MUS("MuseumsandInstitutions"),
MU("Music"),
NA("Nanotechnology"),

    @Getter
    private String label;

    Industry(String label) {
        this.label = label;
    }


   
}
