package com.adv.soft.models;

public enum Skill {
    NETFramework, Abaqus, aboutwork, AcademicAdvising, AcademicWriting, Accountability, Accounting,
    AccountReconciliation, AccountsPayable, AccountsPayableReceivable, ACICodes, Acne, AcousticMeasurement,
    Acquisitions, Acrylic, AcrylicPainting, Action, ActionResearch, ActiveDirectory, ActiveLearning,
    ActivityCoordination, AcuteCare, ADACompliance, Adaptation, AddictionMedicine, AddictionPsychiatry, ADDIE,
    Administration, Administrative, AdministrativeAssistance, Admissions, AdobeCreativeSuite, AdobeIllustrator,
    AdobeInDesign, AdobeLightroom, AdobePremierePro, AdolescentHealth, ADPPayroll, ADSB, AdultCPR, AdultEducation,
    AdvancedCardiacLifeSupportACLS, Adventures, Advertising, Advisory, Aerodynamics, Aeronautics, Aerospace, Aesthetics,
    AffiliateMarketing, AffordableHousing, Aftersales, AgileMethodologies, AgileProjectManagement, Agility,
    Agribusiness, Agricultural, AgronomyAgronomy, AI, Air, Aircraft, AircraftLeasing, AircraftMaintenance,
    AircraftStructures, AircraftSystems, AirForce, AirForceAerospace, AirFreight, AirlinesAirlines, Airports,
    AirspaceManagement, AirTrafficControl, AirTrafficControlAirportManagement, Airworthiness, AlcoholicBeverages,
    AlcoholicBeveragesBartending, AllenBradley, AmazonWeb, Ambulance, Amendment, AmericanHistory, Analitical, Analysis,
    Analytical, AnalyticalChemistry, AnalyticalReasoningCriticalThinking, AnalyticProblemSolving, Analytics,
    AncientHistory, andEnvironmentQHSE, andRehabilitation, Android, AndroidDevelopment, AndroidSDK, AndroidStudio,
    andSafety, Anesthesiology, AngularJS, AnimalCare, AnimalHandling, AnimalHealth, AnimalHusbandry, AnimalModels,
    AnimalNutrition, AnimalWelfare, AnimalWork, Animation, AnimationAfterEffects, Ansible, ANSYS, Antennas,
    Anthropology, AntiMoneyLaundering, Apartments, API, App, Apparel, ApparelFashion, ApplicantTrackingSystems, Applied,
    AppliedLinguistics, APStylebook, Aquaponics, ArcGISProducts, ArchaeologicalSurvey, Archaeology, ArchitecturalDesign,
    Architecture, ArchivalResearch, Archives, Arduino, ArenaSimulationSoftware, Argumentation, Army,
    ArmyMilitaryOperations, ArtConsulting, ArtDirection, ArtEducation, ArtExhibitions, ArtHistory,
    ArtHistoryContemporaryArt, Articulation, ArtificialIntelligence, ArtificialIntelligenceAI, ArtiosCAD,
    ArtisticAbilities, ArtisticEye, ArtisticVision, Artistry, ArtPhotography, ArtsCrafts, ArtsCraftsCrafts,
    AsepticTechnique, AspenHYSYS, Assay, Assessment, AssetManagement, Assistance, Assisting, AssistiveListening,
    AssistiveTechnology, Assurance, ASTMstandards, Astronomy, Athletics, AthleticTraining, Attendance, AudioEditing,
    AudioEngineering, Audiology, AudioMixing, AudioPostProduction, AudioProcessing, AudioRecording, Auditing, AutoCAD,
    AutoCADArchitecture, AutoCADMechanical, Autoclave, Autodesk3dsMax, AutodeskInventor,
    AutodeskRobotStructuralAnalysis, AutomotiveAftermarket, AutomotiveAutomotive, AutomotiveElectronics,
    AutomotiveEngineering, AutomotiveParts, AutomotiveSales, Aviation, AviationSecurity, AvidMediaComposer, Avionics,
    AxureRP, Babysitting, BackgroundArt, BackOfficeOperations, Bacteriology, Bakery, Baking, BalancedLiteracy,
    BalanceSheet, Ballet, BankReconciliation, BanquetOperations, BaseMetals, BasicLifeSupportBLS, Basketball,
    BeautyIndustry, BehavioralDisorders, BehavioralHealth, Benchmarking, Benefits, BenefitsAdministration,
    BiblicalStudies, BigData, BilingualCommunications, Billing, BIM, Biochemistry, Biogeochemistry, Bioinformatics,
    Biology, Biomarkers, Biomaterials, Biomechanics, Biomedical, BiomedicalDevices, BiomedicalEngineering,
    BiomedicalSciences, Biophysics, Biosensors, Biotechnology, Birds, Bitcoin, BitcoinMining, BlendedLearning, Blogger,
    Blogging, BloodBank, BlowMolding, BlueprintReading, BMCRemedyTicketingSystem, BoardofDirectorsReporting, Boat,
    BoatBuilding, Boating, Bodybuilding, Bodypaint, Boilers, Booking, Bookkeeping, BookkeepingAccountsReceivableAR,
    BookReviews, Bootstrap, BotanyBotany, BotoxCosmetic, BrainInjury, Brand, BrandAwareness, Branding, BrandManagement,
    BreachOfContract, Breast, Bridges, Broadcasting, BroadcastJournalism, BroadcastTelevision, Budgeting,
    BudgetManagement, BuildingAutomation, BuildingInformationModeling, BuildingManagementSystems, BuildingMaterials,
    BuildingServices, BuildStrongRelationships, Business, BusinesstoBusinessB2B, BusinessAlliances, BusinessAnalysis,
    BusinessCoaching, BusinessDecisionMaking, BusinessEnglish, BusinessIntelligenceBI, BusinessLitigation,
    BusinessModeling, BusinessPlanning, BusinessProcess, BusinessProcessMapping, BusinessRelationshipBuilding,
    BusinessRelationshipManagement, BusinessTransactions, BusinessTravel, C, Cabinetry, CADCAM, Cadastral, Cake, Cakes,
    Calculations, Calculus, Calendaring, Calibration, Calling, CallMonitoring, Camera, Cancer, CancerBiology,
    CancerImmunotherapy, CancerResearch, CancerScreening, CanDoApproach, CapacityBuilding, CapitalMarkets,
    CapitalMarketsRiskManagement, CapitalRaising, Carbon, CarbonFiber, CarbonNanotubes, CardiacSurgery,
    CardiologyCardiology, CardiovascularDisease, CareerCounseling, CarpentryCarpentry, CarpetCleaning, Cartography,
    CascadingStyleSheetsCSS, Cash, CashCollection, CashFlow, CashHandling, Cashiering, CasinoGaming, Cataloging,
    Catering, Catheters, CATIA, CellBiology, CentralNervousSystem, CertifiedArborist, CFX, ChainofTitle, Chainsaw,
    Champagne, Change, ChangeControl, ChangeManagement, ChannelAccountManagement, ChannelRelationshipManagement,
    Chapter11, Characterization, CharityWork, Charter, ChemicalIndustry, ChemicalProcessingChemicalEngineering,
    Chemotherapy, Chess, ChildAdvocacy, Childcare, ChildDevelopment, ChildHealth, ChildPsychiatry, ChildWelfare,
    Choreography, Chromatography, ChronicPain, ChurchEvents, CircuitsIC, Cisco, CivilAviation, CivilLaw,
    ClaimsManagement, ClassicalBallet, ClassroomManagement, Cleaning, ClericalSkills, Clientfocused, ClientBilling,
    ClientProspecting, ClientRapport, ClientRelations, Climate, Climatology, Clinical, ClinicalDevelopment,
    ClinicalResearch, ClinicalTrials, CLO, ClosedCircuitTelevisionCCTV, ClosingEntries, CloudComputing, CNC,
    CNCProgramming, CNSdisorders, Coaching, CoachingMentoring, Coal, Coalitions, Coatings, CognitiveBehavioral, Cold,
    Collaboration, CollaborationSolutions, CollaborativeProblemSolving, CollaborativeWork, CollectionDevelopment,
    ColorManagement, Combustion, Comedy, Commercial, CommercialAviation, CommercialAwareness, CommercialBanking,
    CommercialBankingFinancialServices, CommercialCleaning, CommercialFishing, CommercialInsurance, Commercialization,
    CommercialLeasing, CommercialLitigation, CommercialPhotography, CommercialRealEstate, Commercials, Commissioning,
    Communication, Communications, CommunicationsSecurity, Community, CommunityDevelopment, CommunityEngagement,
    CommunityManagement, CommunityOutreach, CommunityPharmacy, CommunityService, Company, CompanyValuation,
    Compensation, CompensationBenefits, Competitive, CompetitiveAnalysis, CompetitiveIntelligence, Complaint,
    ComplaintManagement, Completion, CompositeApplications, CompositesComposites, Comprehension, ComprehensivePlanning,
    ComputedTomography, Computer, ComputerAidedDesignCAD, ComputerAidedEngineeringCAE, ComputerGraphicsComputerGraphics,
    ComputerHardware, ComputerLiteracy, ComputerNetworking, ComputerNumericalControl, ComputerVision,
    ConceptDevelopment, ConceptualArt, ConceptualArtMixedMedia, Concierge, Concrete, ConcreteMaterials, Conflict,
    ConflictAnalysis, ConflictManagement, ConflictResolution, Confluence, ConfocalMicroscopy, ConsciousSedation,
    ConsolidatedFinancialStatements, Consolidation, ConstitutionalLawConstitutionalLaw, Construction,
    ConstructionDrawings, ConstructionManagement, ConstructionSafety, ConsultativeSelling, Consulting,
    ConsumerElectronics, ConsumerGoodsFMCG, ConsumerMarketing, ContactCenters, ContactLenses, ContainerShipping,
    ContemporaryDance, Content, ContentManagement, ContentManagementSystemsCMS, ContentStrategy, ContinuousImprovement,
    Contracting, ContractLaw, ContractLawCivilLitigation, ContractManagement, ContractNegotiation, Contractors,
    ContractRecruitment, ContractualAgreements, ContractWriting, Controls, ControlSystemsDesign, Conveyancing,
    ConvincingPeople, CookingCooking, Cooperation, Cooperative, Coordination, CopyEditing, Copywriting, Corporate,
    CorporateCommunications, CorporateDevelopment, CorporateEvents, CorporateFinance, CorporateGovernance, CorporateLaw,
    CorporateSocial, CorporateTax, CorrectiveandPreventiveActionCAPA, Corrugated, CosmeticDentistry, Cosmetology,
    CosmetologyCosmetics, CostAccounting, CostumeDesign, CounselingPsychology, Counterinsurgency, Counterterrorism,
    CProgrammingLanguage, CreativeArts, CreativeCampaign, CreativeConception, CreativeContent, CreativeContentCreation,
    CreativeProblemSolving, CreativeSkills, CreativeVisualization, CreativeWork, CreativeWriting, CreativitySkills,
    Credit, CreditCards, CreditControl, CreditRisk, Creo, CrimeSceneInvestigations, CriminalDefense, CriminalJustice,
    CriminalLawCriminalLaw, CrisisCommunications, CrisisIntervention, CrisisManagement, CriticalCareNursing,
    CriticalReading, Criticism, CRMIntegration, Crochet, CROManagement, CropProtection, CrossborderTransactions,
    Crosscultural, CrossculturalCommunicationSkills, CrossfunctionalCoordination, CrossfunctionalTeam, Crossteam,
    CrossFit, CrossFunctionalTeamBuilding, CrossMerchandising, Cryptocurrency, CryptocurrencyTrading, CulinarySkills,
    CulturalAnthropology, CulturalAwareness, CulturalDiversity, CulturalHeritage, CulturalResourceManagement,
    CulturalStudies, Curating, CurriculumDevelopment, CurriculumMapping, Customer, CustomerAcquisition, CustomerContact,
    CustomerEngagement, CustomerExperience, CustomerInsight, CustomerLoyalty, CustomerProductTraining,
    CustomerRelationshipManagementCRM, CustomerRetention, CustomerSatisfaction, CustomerService,
    CustomerServiceManagement, CustomerServiceSystems, CustomerSupport, Cybersecurity, CybersecuritySecurity, CycleSDLC,
    CyclicVoltammetry, CYPE, DairyProducts, DanceDance, DanceEducation, DanceInstruction, Data, Datadriven,
    DatadrivenDecision, DataAcquisition, Databases, DataCenter, DataDrivenTesting, DataEntry, DataPrivacy,
    DataProtectionAct, DataScienceDataAnalysis, DataStorage, DataStructures, DCS, Deadline, DealerManagement,
    DebtCollectionDebtCollection, DebtConsolidation, DebtManagement, Debtors, DebtRestructuring, DebtSettlement,
    DecisionMaking, DecisionAnalysis, DecisionModeling, DecisionSupport, Decisiveness, Decommissioning, Deconstruction,
    Decorating, Decoration, DeepLearning, Defense, DeferredCompensation, DeferredRevenue, DeliveryOperationsFreight,
    DemandGeneration, DemandPlanning, Demography, Dental, DentalCare, DentistryDentistry, DermalFillers,
    DermatologyDermatology, Design, DesignEngineering, DesignofExperimentsDOE, DesignResearch, DesignStrategy,
    DesktopComputers, Development, DevelopmentalBiology, DevelopmentLife, DevelopmentToolsJava, Devices, Diabetes,
    Dialysis, DICOM, DifferentiatedInstruction, DigestiveDisorders, Digital, DigitalImaging,
    DigitalLiteracyMicrosoftOffice, DigitalMarketing, DigitalMedia, DigitalPhotography, DigitalPrinting,
    DigitalPublishing, DigitalSignalProcessing, DigitalStrategy, DigitalXray, Digitization, Diplomacy, DirectSales,
    DirectStoreDelivery, DisabilityRights, DisasterRecovery, Discipleship, DiscourseAnalysis, Discretion,
    DiscriminationLaw, Disease, Disorders, Dispatching, Disposables, Dispositions, DistanceLearning,
    DistributedControlSystem, Distribution, DiversityInclusion, Diving, DivorceLaw, DNA, DNAExtraction, Document,
    Documentaries, Documentation, Dog, DogBehavior, Dogs, DogTraining, DomainManagement, DomainNameSystemDNS,
    DomainRegistration, DoneGTDMethod, DrainageSystems, Drama, Drilling, DrillingEngineeringProjectEngineering, Drives,
    DronePiloting, DrugDevelopment, DryEye, DualDiagnosis, DueDiligence, Dutch, DynamicPositioning, Dynamics, Dysphagia,
    Ecommerce, EcommerceOptimization, ELearning, Early, EarlystageStartups, EarlyChildhoodDevelopment,
    EarlyChildhoodEducation, EarlyChildhoodLiteracy, EarthScience, Echocardiography, Ecology, Econometrics, Economic,
    EconomicsEconomics, EditingEditing, EditorialProcess, Educational, EducationalAssessment, EducationalConsulting,
    EducationalLeadership, EducationalManagement, EducationalResearch, EducationalTechnology, EducationalWorkshops,
    Efficiency, EHS, ElderLaw, ElectionLaw, Electrical, ElectricalDesign, ElectricalSafety, ElectricalTroubleshooting,
    ElectricalWiring, Electricity, ElectricPower, Electromechanical, ElectromyographyEMG, ElectronicControl,
    ElectronicDataCaptureEDC, ElectronicInstrumentation, ElectronicMedicalRecordEMR, Electronics,
    ElectronicsElectronics, ElectronicWarfare, ElementaryEducation, ELISA, EmailClients, EmailMarketing, EmbeddedC,
    EmbeddedSystems, Embroidery, Emcee, Emergency, EmergencyManagement, EmergencyMedicalServicesEMS, EmergencyMedicine,
    EmergencyPlanning, EmergencyServices, EmotionalIntelligence, Employee, EmployeeBenefitsDesign, EmployeeEngagement,
    EmployeeGrievance, EmployeeLearningDevelopment, EmployeeRecognition, EmployeeTraining, EmploymentContracts,
    EmploymentLaw, EmploymentLawCompliance, EmploymentLitigation, EMT, Encoding, Endodontics, Endoscopy, Endurance,
    EnergyEfficiency, EnergyIndustry, EnergyManagement, EnergyMarkets, Engagement, Engineering, EngineeringDrawings,
    EngineeringGeology, EnglishasaSecond, EnglishGrammar, EnglishLiterature, EnglishTeaching, EnglishtoSpanish,
    EnglishTranslation, EnterpriseArchitecture, EnterpriseMarketing, EnterpriseResourcePlanningERP, EnterpriseSoftware,
    EntertainmentIndustry, Entomology, Entrepreneurship, Environment, Environmental, EnvironmentalAwareness,
    EnvironmentalCompliance, EnvironmentalConsulting, EnvironmentalEngineering, EnvironmentalImpactAssessment,
    EnvironmentalManagementSystems, EnvironmentalPolicy, EnvironmentalScience, EPC, EpicSystems, Epidemiology,
    EqualEmploymentOpportunityEEO, EquipmentManagement, Equities, Ergonomics, ErosionControl, ERPSoftware, Essays,
    EstateDevelopment, EstateLaw, Ethereum, EthicalDecisionMaking, Ethics, Ethnobotany, Ethnography, EuropeanHistory,
    EuropeanPolitics, EuropeanStudies, EuropeanUnion, EventManagement, EventPhotography, EventPlanningEventPlanning,
    EventProduction, Evictions, EvidenceBasedPracticeEBP, EViews, Evolution, EvolutionaryBiology,
    EvolutionaryBiologyMicrobiology, Excavation, Executive, ExecutiveSearch, ExercisePrescription, ExitSurveys,
    ExoticAnimals, ExpenseReports, Experience, ExpertWitness, Export, Expression, ExternalAudit, Extrusion, EyeExams,
    Eyewear, Facebook, Factchecking, Factoring, Family, FamilyLawFamilyLaw,
    FamilyMedicineCardiopulmonaryResuscitationCPR, FamilyTherapy, Farms, Fashion, FashionDesign, FashionIllustration,
    FashionJewelry, FashionPhotography, FastMoving, FDAGMP, Feature, FederalGovernmentRelations, FEManalysis, Fertility,
    Festivals, Fiberglass, Fibre, FieldProgrammableGateArraysFPGA, FieldInstruments, FieldWork, Filing, Fillers, Film,
    FilmProduction, Filtration, FIN48, FinalCut, Financial, FinancialAccounting, FinancialAdvisory, FinancialAnalysis,
    FinancialAudits, FinancialMarkets, FinancialModeling, FinancialPlanning, FinancialReporting, FinancialRisk,
    FinancialTechnology, FinancialTranslation, Fine, FineDining, FinishCarpentry, FiniteElementAnalysisFEA, FinTech,
    FinTechBlockchain, Firebase, Firefighting, Firewalls, First, FirstAid, FirstAidTraining, FishingFishing, Fitness,
    FitnessInstruction, FitnessTraining, FleetManagement, FlexibleApproach, FlexibleApproachEasilyAdaptable,
    FlexibleSchedule, FlightPlanning, FlightSafety, FlightTraining, FloorCleaning, Flooring, FloralDesign,
    FluidDynamics, FluidMechanics, FluidMechanicsComputationalFluidDynamicsCFD, Fluids, FlyFishing, FoldingCartons,
    Food, FoodIndustry, FoodManufacturing, FoodMicrobiology, FoodPackaging, FoodPhotography, FoodPreparation,
    FoodProcessing, FoodQuality, FoodSafety, FoodSafetyManagementSystem, FoodScience, FoodService, FoodTechnology,
    Football, FootballCoaching, Force, Forecasting, ForeignAffairs, ForeignLanguages, ForeignLanguagesEnglish,
    ForensicAccounting, ForensicPsychiatry, ForestManagement, ForestProducts, ForestryForestry, ForkliftOperation,
    FormulationChemistry, Fortran, Forwarding, Fragrance, FreightForwarding, FreightTransportation, French, FrontOffice,
    Frozen, FuelManagement, FunctionalTesting, FundamentalAnalysis, Fundraising, Furnishings, Furniture, Gallery,
    GameDesign, GameDevelopment, GameDevelopmentUnity, Games, Gaming, GamingIndustry, Gap, GardenDesign, Gardening, Gas,
    GasChromatography, GastroenterologyGastroenterology, GastrointestinalDisorders, GastrointestinalSurgery,
    GelElectrophoresis, Genealogy, GeneralAnesthesia, GeneralInsurance, GeneralLedger,
    GenerallyAcceptedAccountingPrinciplesGAAP, GeneralManagement, GeneralSurgery, GeneralSurgerySurgery,
    GeneticEngineering, Genetics, Genomics, GeographicInformationSystemsGIS, GeologicalMapping, Geology,
    GeometricDimensioningTolerancing, Geotechnical, GeotechnicalEngineering, GeriatricPsychiatry, German, GettingThings,
    GIMP, Git, Glaucoma, Global, GlobalDelivery, GlobalHealth, GlobalPositioningSystem, GlobalStrategy, GoalAnalysis,
    Gold, Golf, Good, GoodClinicalPracticeGCP, GoodManufacturingPracticeGMP, GoodsandServicesTaxGST, GoogleAds,
    GoogleAnalytics, GotomarketStrategy, Government, GovernmentalAffairs, GovernmentLiaison, GovernmentRelations, GPS,
    Grammar, GramStaining, Grant, GraphicDesign, GraphicDesignAdobePhotoshop, GrossMargin, Ground, GroupExercise,
    GroupPresentations, GroupTherapy, GroupWork, Growth, GrowthStrategies, GSM, Guardianship, Guest, Guided, Gymnastics,
    Gynecology, HabitatRestoration, Hacking, HairCare, HairCutting, HairStyling, Handel,
    HazardAnalysisandCriticalControlPointsHACCP, Hazardous, HazardousMaterials, HAZOPStudy, Healing, Healthcare,
    HealthcareInformation, HealthcareManagement, HealthEconomics, HealthEducation, HealthInformatics, HealthInsurance,
    HealthPhysics, HealthPromotion, HearingAids, HeartFailure, HeatTransfer, HeavyEquipment, HedgeFunds,
    HelicopterOperations, Helicopters, Hepatology, HeterogeneousCatalysis, High,
    HighPerformanceLiquidChromatographyHPLC, Highdegreeofinitiative, HigherEducation, HighLevelOfAccuracy, HighVoltage,
    Highway, Highways, HipHopDance, Hiring, Histology, Historical, HistoricalResearch, HistoricPreservation,
    HistoryHistory, HolisticHealth, HomeCare, HomeCleaning, HomelandSecurity, HORECA, HorseTraining, Horticulture,
    HospitalityIndustry, Hospitals, Host, HostedServices, HostingServices, Hotel, HotelManagement, HotWater, House,
    Housekeeping, HR, HRConsulting, HRPolicies, HTML, HTML5, HubSpot, HumanCapitalManagement, HumanComputer,
    Humanitarian, HumanResources, HumanResourcesHR, HumanRights, Hunting, HVAC, HydraulicCalculations, Hydraulics,
    HydrologicModeling, Hydropower, Hyperledger, Hypermesh, Hypertension, I9Compliance, IATA, IBMSPSS, Illustration,
    Image, ImageAnalysis, ImageEditing, ImageProcessing, ImageSegmentation, ImmigrationLaw, Immunofluorescence,
    Immunology, Import, Improvisation, InboundLeadGeneration, InboundMarketing, IncidentInvestigation, IncomeTax,
    Independence, IndependentThinking, IndustrialAutomation, IndustrialCleaning, IndustrialControl, IndustrialDesign,
    IndustrialDesignDesignThinking, IndustrialSafety, Infertility, InfluenceOthers, InfluencerMarketing, Information,
    InformationAnalysis, InformationLiteracy, InformationManagement, InformationSecurity, InformationSecurityManagement,
    InjectionMolding, InjuryPrevention, Innovation, InnovationDevelopment, InnovationManagement, InorganicChemistry,
    InorganicSynthesis, InpatientCare, InsideSalesAccountManagement, Inspection, Instagram, InstallationDesign,
    InstructionalDesign, InstrumentalAnalysis, InstrumentationInstrumentation, InsuranceInsurance, IntangibleAssets,
    Integrated, IntegratedMarketing, Integration, Integrity, IntellectualPropertyIntellectualProperty, Intelligence,
    IntelligenceAnalysis, Interaction, InteractionDesign, Interagency, InterculturalCommunication, InterculturalSkills,
    InterdisciplinaryCollaboration, Interferometry, InteriorArchitecture, InteriorDesignInteriorDesign, InternalAudit,
    InternalCommunications, InternalControls, InternalMedicine, InternationalArbitration, InternationalBusiness,
    InternationalBusinessDevelopment, InternationalDevelopment, InternationalEconomics,
    InternationalFinancialReportingStandardsIFRS, InternationalFlightOperations, InternationalLaw,
    InternationalLogistics, InternationalNegotiations, InternationalRelations, InternationalSales,
    InternationalSecurity, InternationalTax, InternationalTrade, InternetProtocolIP, InternetProtocolSuiteTCPIP,
    InternetServices, InterpersonalCommunication, InterpersonalRelationships, Intervention, InterventionalCardiology,
    Interviewing, Intraoperative, Intubation, Inventory, InventoryControl, InventoryManagement, InventoryPlanning,
    Investigation, Investigations, InvestmentBanking, InvestmentProperties, Investments, InvestorPresentations,
    InvestorRelations, InvestorReporting, InVitro, InvoiceDiscounting, InvoiceProcessing, Invoicing, iPhone, IronOre,
    Irrigation, ISMCode, ISO, ISO14971, ISO17025, IT, Italian, ItalianCuisine, ITAudit, ITConsulting, ITIL, ITLaw,
    ITRecruitment, ITServiceManagement, ITStrategy, IVR, JDEdwards, Jewelry, JewelryDesign, Jira, Joinery,
    JournalEntries, JournalismJournalism, jQuery, Juvederm, JuvenileLaw, K12Education, Kaizen, Kalmanfiltering,
    KeyAccountRelationshipBuilding, KeyOpinionLeaders, Keyshot, KidneyTransplant, Kinesiology,
    KinesiologyExercisePhysiology, KitchenCabinets, Knee, KnowledgeManagement, Kotlin, KPIReports, Kronos,
    KronosTimekeeping, Laborand, LaborandEmploymentLaw, LaboratoryAnimalMedicine, LaboratoryEquipment,
    LaboratoryInformationManagementSystemLIMS, LaboratoryMedicine, LaboratoryPracticeGLP, LaboratorySafety,
    LaboratorySkills, LaboratoryTechniques, LabourIssues, Land, Landscape, LandscapeArchitecture, LandscapeDesign,
    Landscaping, LandSurveyingLandSurveying, LandUseLaw, LandUsePlanning, LanguageDisorders, LanguageESL,
    LanguageServices, LanguageTeaching, LaparoscopicSurgery, Laser, LaserScanning, LatinAmericanStudies, Law,
    LawEnforcement, LawLegalResearch, LawnCare, Lead, Leadership, LeadershipDevelopment, LeadGeneration,
    LeanManufacturing, LeanStartup, Learning, LearningManagement, LearningManagementSystems, Lecturing, LegalAdvice,
    LegalAssistance, LegalDescriptions, LegalTranslation, LegalWriting, Legislation, LegislativeAffairs,
    LegislativeRelations, LegislativeResearch, Leica, LeisureIndustry, LeisureTravel, Lenses, LessonPlanning, Lettings,
    Leveling, Liability, LibraryInstruction, LibraryManagement, LibraryResearch, LibraryScience,
    LibraryScienceLibraryServices, Licensing, LifeCoaching, LifeInsurance, LifeSciences, LifeSkills, Lighting,
    Lightning, LinearAccelerators, LinguisticsLinguistics, Linux, Liposuction, Liquidation, Listen, Literacy, Literary,
    LiteratureLiterature, Litigation, LiveEvents, Loans, Lobbying, LocalGovernment, Localization, LogicalApproach,
    Logistics, LogisticsAnalysis, LogisticsManagement, LogisticSupport, LogoDesign, LossPrevention, LowIncomeHousing,
    LowBackPain, LTE, LTLShipping, LuxuryGoods, Mac, MachineDesign, MachineLearning, MachineTools, Machining,
    Macroeconomics, Magazines, Magento, MailServer, Maintenance, MaintenanceManagement, MaintenanceRepair,
    MakeThingsHappen, MakeupArtistry, Making, ManagedCare, ManagedHosting, Management, ManagementAccounting,
    ManagementConsulting, ManagerialFinance, Manuals, ManualTesting, ManualTherapy, Manufacturing,
    ManuscriptDevelopment, MarineConservation, MarineIndustry, MarineOperations, MarinePropulsion, MarineSurvey,
    Maritime, MaritimeOperations, MaritimeSecurity, MarketAccess, MarketAnalysis, Marketing,
    MarketingCommunicationsPlanning, MarketingEventPlanning, MarketingManagement, MarketingStrategy, MarketIntelligence,
    MarketPlanning, MarketResearch, MartialArts, MaterialsManagement, MaterialsScience, MaterialsScienceMaterials,
    Maternity, Mathcad, Mathematica, MathematicalModeling, Mathematics, MathematicsMathematics, Maxsurf, Maya,
    Measurements, MechanicalAnalysis, MechanicalProductDesign, MechanicalProperties, MechanicalVentilation, Mechanics,
    Mechatronics, MediaRelations, Mediation, Medical, MedicalSurgical, MedicalAffairs, MedicalDeviceRD, MedicalDevices,
    MedicalDiagnostics, MedicalEducation, MedicalEquipment, MedicalLaw, MedicalMicrobiology, MedicalRecords,
    MedicalTechnology, MedicalUltrasound, Medicare, Medication, Medicine, MedicineMedicine, MeetingPlanning,
    Memorization, MentalHealth, MentalHealthCounseling, MentalHealthTreatment, Mentoring, Menu, Merchandising,
    MergersAcquisitionsMA, Metadata, MetalFabrication, Metallurgy, Methodologies, MetricsReporting, Metrology,
    Microbiology, Microcontrollers, Microeconomics, MICROS, Microscopy, MicrosoftAccess, MicrosoftAzure,
    MicrosoftDynamics, MicrosoftDynamicsCRM, MicrosoftExcel, MicrosoftExchange, MicrosoftOutlook, MicrosoftPowerPoint,
    MicrosoftProject, MicrosoftSQLServer, MicrosoftWord, Midas, Midwifery, MilitaryAviation, MilitaryHistory,
    MilitaryTraining, Millwork, MineralProcessing, Minerals, MiningEngineering, MiningMining, Mobile, MobileApplication,
    MobileApplications, MobileCommunications, MobileDeviceManagement, MobileDevices, MobileMarketing, ModernDance, Mold,
    MolecularBiology, MolecularCloning, MolecularDynamics, MolecularMicrobiology, MolecularModeling, MongoDB,
    Monitoring, MonteCarloSimulation, Moodle, MortgageLending, Mosaics, MotionGraphics, MotivationalInterviewing,
    MotivationalSpeaking, Motors, MouldDesign, Mountaineering, MovementDisorders, MRI, Multitasking, Municipalities,
    MusculoskeletalPhysiotherapy, MuseumCollections, MuseumEducation, Museums, MusicComposition, MusicEducation,
    MusicIndustry, MusicMusic, MusicProduction, MutualFunds, MYOB, MySQL, Nanoelectronics, Nanomedicine, Nanostructures,
    NanotechnologyNanotechnology, Narrative, NationalSecurity, NaturalGas, NaturalLanguageProcessingNLP, NAV,
    NavalArchitecture, NavalArchitectureMarineEngineering, Navigation, Navy, NavyCommand, NeckPain, Needs,
    NegotiationNegotiation, NeonatalIntensiveCare, NeonatalNursing, Neonatology, Nephrology, NetworkAdministration,
    Networking, NetworkMarketing, NetworkSecurity, NetworkVPN, NeurologicalDisorders, NeurologicalRehabilitation,
    Neurologists, NeurologyNeurology, Neuroscience, Neurosurgery, NewBusinessOpportunities, Newsletters, Newspapers,
    NewsWriting, NICECallRecording, Nightclub, NIRSpectroscopy, NMR, NonGovernmentalOrganizationsNGOs,
    NonprofitVolunteering, NondestructiveTestingNDT, Nonprofit, NonprofitOrganizations, NoteTaking, Novels,
    NuclearEnergy, NuclearEngineering, NuclearEngineeringNuclear, NuclearMagneticResonanceNMR, NuclearPhysics,
    NuclearPhysicsRadiationSafety, NuclearPowerPlants, NuclearProliferation, NuclearSafety, Numeracy, NumericalAnalysis,
    NumericalSimulation, Nursing, Nutrition, NutritionalCounseling, Obstetrics, ObstetricsandGynecology,
    ObstetricsWomensHealth, Occupational, Oceanography, OceanographyScubaDiving, OceanTransportation, Ocular, Office365,
    OfficeAdministration, OfficeCleaning, OfficeManagers, OffsetPrinting, OffshoreDrilling, OffshoreOperations,
    OHSAS18001, Oilfield, OilGas, OilGasIndustry, OilGasPetroleum, OilPainting, Onboarding, Oncology,
    OncologyClinicalResearch, Online, OnlineAdvertising, OnlineGaming, OnlineJournalism, OnlineMarketing, OnlineTravel,
    OnshoreOperations, OpenCV, OpenFOAM, OpenGL, OpeningHotels, OperatingRoom, OperatingSystems, Operational,
    OperationalEfficiency, OperationalPlanning, Operations, OperationsManagement, OperationsResearch,
    OphthalmologyOphthalmology, Opticians, Optics, Optimization, Optometry, OracleDatabase, OralCommunication,
    OralComprehension, OralComprehensionLearningDisabilities, OralHistory, OralSurgery, OrderAdministration,
    OrderManagement, OrderPicking, OrganicChemistry, OrganicFarming, OrganizationalDevelopment,
    OrganizationalLeadership, OrganizationSkills, Oriented, Ornithology, OrthopedicSurgeryOrthopedicSurgery, Orthotics,
    Osteoporosis, Outdoor, OutpatientOrthopedics, Outsourcing, Ownership, Pack, Packaging, PackagingEngineering,
    PackagingMachinery, PACS, PainManagement, Paint, Pandas, PaperIndustry, Paramedic, Parasitology, Partner,
    PartnerRelationshipManagement, Partnerships, Passionate, PastoralCare, PastoralCounseling, Pastry, Patent,
    Patentability, PatentLaw, PatentLitigation, PatentPreparation, Pathology, PathologyFlowCytometry, PatientAdvocacy,
    PatientEducation, PatientSafety, PayPerClickPPC, PayrollAdministration, PayrollManagement, PayrollProcessing,
    PayrollServices, PayrollServicesPayroll, PayrollTaxes, Pedagogy, PediatricCPR, PediatricHematologyOncology,
    PediatricsPediatrics, PediatricSurgery, PediatricUrology, PenetrationTesting, People, PeopleDevelopment,
    PeopleManagement, PeopleSoft, Perceptiveness, Perforce, Performance, PerformanceComputingHPC,
    PerformanceImprovement, PerformanceManagement, PerformanceMotivation, Periodontics, Persistence, PersonalCare,
    PersonalCoachingCoaching, PersonalDevelopment, PersonalTraining, PersonnelManagement, Persuader,
    PersuasionPersuasion, Persuasive, PersuasivePresentations, PetCare, Petrochemical, Pharmaceutical,
    PharmaceuticalSales, Pharmaceutics, Pharmacology, Pharmacovigilance, Pharmacy, PhoneEtiquette, Phonetics,
    Photography, PhotographyPhotography, Photojournalism, Photonics, PhotoRetouching, PhotoShoots, PHP,
    PhysicalMedicine, PhysicalOceanography, PhysicalSecurity, PhysicalTherapy, Physicians, PhysicsPhysics,
    PhysiologyCellCulture, Pick, PictureArchivingandCommunicationSystem, PileFoundations, Piloting, Pipelines, Piping,
    PipingandInstrumentationDrawingPID, PitchingIdeas, PivotTables, PLSQL, Plant, PlantBiology, PlantBreeding,
    PlantEcology, PlantGenetics, PlantIdentification, PlantPhysiology, PlantPropagation, PlasticExtrusion,
    PlasticPartDesign, Plastics, PlasticsIndustry, PlasticsPlastics, PlasticSurgery, PLCLadderLogic, PLCProgramming,
    PLCSiemens, PLManagement, Pneumatics, Podcasting, Podiatry, Poetry, PointofPurchase, PointofSalePOS, PolicyAnalysis,
    PolicyDevelopment, PoliticalCampaigns, PoliticalConsulting, PoliticalPhilosophy, Politics,
    PolymeraseChainReactionPCR, PolymerComposites, Polymers, POPDisplays, PortfolioManagement, PortraitPhotography,
    Ports, Portuguese, Positioning, PositiveWorkEnvironment, Postfix, PostgreSQL, Power, PowerElectronics, PowerPlants,
    Powershell, PowerSystems, PowerSystemsPowerGeneration, Powertrain, Pragmatics, Preopening, Prepress, Presales,
    Preaching, PreciousMetals, Precommissioning, Pregnancy, PrenatalCare, PreparationofWills, Preschool, Presentations,
    PresentationSkills, Presenter, PressReleases, Pressure, PressureHandling, PrestressedConcrete, Prevention,
    PreventiveMaintenance, Pricing, PricingStrategy, PrimaveraP6, PrintedCircuitBoardPCB, Printing, Printing3DPrinting,
    Printmaking, PrintManagement, PrioritizeWorkload, PriorityManagement, PrivateClients, Pro, ProbateLaw,
    ProblemAnalysis, ProblemSolving, Process, ProcessAutomation, ProcessDesign, ProcessEfficiency, ProcessEngineering,
    ProcessFlow, ProcessImprovement, Processing, ProcessScheduler, Procurement, Product, ProductDesign,
    ProductDevelopment, Production, ProductLaunch, ProductLifecycleManagement, ProductMarketing, ProductPhotography,
    ProductStrategy, ProductTesting, Professional, ProfessionalCleaning, ProfessionalCommunication,
    ProfessionalLiability, ProfessionalPhoneSkills, ProfessionalSportsSportsManagement, ProgramDevelopment,
    ProgramEvaluation, ProgrammableLogicControllerPLC, ProgramManagement, Project, ProjectCoordination, ProjectDesign,
    ProjectEstimation, ProjectManagement, ProjectPlanning, Proofreading, Property, PropertyCasualtyInsurance,
    PropertyDamage, PropertyLawPropertyLaw, PropertyManagement, PropertyManagementSystems, ProposalWriting, Prosecution,
    Prosthetics, Prosthodontics, Protection, Protein, ProteinPurification, Psychiatry, Psychology, Psychotherapy,
    PublicHealthPublicHealth, PublicLiability, PublicPolicy, PublicSafety, PublicSector, PublicSpeaking, Publishing,
    Pulmonology, Pump, Pumps, Punctuation, PurchaseManagement, PurchaseOrders, PVSyst, PythonProgrammingLanguage,
    QAEngineering, QAQC, Qt, Qualitative, QualitativeQuantitativeResearch, QualitativeResearch, Quality,
    QualityAuditing, QualityControl, QualityManagement, QualitySystem, Qualtrics, QuantitativeAnalytics,
    QuantitativeData, QuantitativeResearch, QuantumChemistry, QuantumGIS, QuickBooks, R, Radar, Radiation,
    RadiationDetectors, RadiationEffects, Radio, RadioactiveMaterials, RadioAdvertising, RadioBroadcasting,
    RadioFrequency, Radiography, Radiology, RadiologyMedicalImaging, RadioProduction, RadioProductionRadio,
    RadioPromotions, RailTransport, RapidPrototyping, RaspberryPi, RawMaterials, ReactionqPCR, Reactor, ReactorPhysics,
    Reading, ReadingComprehension, ReadingIntervention, Real, RealTimePolymeraseChain, RealEstate,
    RealEstateTransactions, Reasoning, ReasoningSkills, Rebates, Receiving, ReceptionistDuties, RecordKeeping,
    RecordsManagement, Recreation, RecreationOutdoorRecreation, Recruiting, RecruitingRecruiting, RefineryOperations,
    Refurbishments, RegionalAnesthesia, Regression, Regulations, RegulatoryCompliance, Rehabilitation, Relations,
    RelationshipBuilding, RelationshipDevelopment, RelationshipMarketing, Relativity, Religion,
    ReligiousStudiesTheology, Remediation, RemoteSensing, Rendering, RenewableEnergy, RenewableResources, Renovation,
    Rentals, Repair, Reporting, ReportWriting, RequirementsAnalysis, RequirementsGathering, Research,
    ResearchandDevelopmentRD, ResearchDesign, Reservations, ResidentialRealEstate, Resiliency, Responsibility,
    ResponsibleServiceofAlcohol, RestaurantManagement, Restoration, RestorativeDentistry, Restructuring, Retail,
    RetailBanking, RetailPackaging, RetailPackagingPackagingDesign, RetailSales, RetirementPlanning,
    ReturnonInvestmentAnalysis, RevenueAnalysis, RevenueCycle, RevenueEnhancement, RevenueForecasting,
    RevenueRecognition, Revit, RF, RiskAssessment, Road, RoadConstruction, RoboticProcessAutomationRPA, Robotics,
    RoboticsAutomation, RockClimbing, Roofers, RoomsDivision, RootCauseProblem, RTK, Safeguarding, SafeguardingChildren,
    Safety, SafetyManagementSystems, Sailing, Salary, Sales, SalesEffectiveness, Salesforcecom,
    SalesforcecomAdministration, SalesLeads, SalesMarketing, SalesOperations, SalesProcess, SalesProspecting,
    SalesStrategy, SalesTax, SalesTrainings, SAPERP, SAPImplementation, SAPProducts, SarbanesOxleyAct, SASS, SCADA,
    ScalableVectorGraphicsSVG, ScanningElectronMicroscopySEM, ScheduleControl, SchedulingManagement, SCIClearance,
    Science, ScientificComputing, ScientificComputingMATLAB, Screening, ScreenPrinting, ScriptEditing, Scrum, Sculpture,
    Seamanship, SearchEngineMarketingSEM, SearchEngineOptimization, SECFinancial, SecondaryEducation, SecondLanguage,
    SecondLanguageAcquisition, SecurityManagement, SecurityOperations, Sedation, SeedProduction, SeismicDesign,
    Selenium, Selfmanagement, Selfconfidence, SelfLearning, Sellers, Semiconductors, Semiotics, Sensors, SEO, Serology,
    Servers, ServiceDelivery, ServiceManagement, Services, ServicesAWS, SetDesign, Sewing, SharePoint, Shipbuilding,
    ShipManagement, Shipping, Shipyards, ShortStories, Signal, SignalProcessingSignalProcessing, Simulink, Singing,
    SingleFamilyHomes, SixSigma, Sketch, Sketching, SketchUp, SkilledMultitasker, SkinCancer, SkinCare, SkipTracing,
    SmallBusiness, SMO, Soccer, SoccerCoaching, Sociability, Social, SocialAnthropology, SocialChange,
    SocialEntrepreneurship, SocialJustice, SocialMediaAdvertising, SocialMediaBlogging, SocialMediaCommunications,
    SocialMediaMarketing, SocialMediaOptimization, SocialMediaSocialMedia, SocialResearch, SocialResponsibility,
    SocialSecurityLaw, SocialSelling, SocialServices, SocialServicesCaseManagement, SocialWork, SociologySociology,
    Software, SoftwareasaServiceSaaS, SoftwareDesign, SoftwareDevelopmentLife, SoftwareDocumentation,
    SoftwareInstallation, SoftwareTesting, SoftwareTestingTesting, SoilFertility, SoilSampling, SoilScience,
    SolarEnergy, Solidity, SOLIDWORKS, SolutionArchitecture, SolutionFocused, SolutionSelling, Solving, Sound, Sourcing,
    Spa, SpacePlanning, Spanish, SpanishTranslation, SpatialAnalysis, Speaker, SpecialEducation, SpecialEvents,
    Specifications, Spectroscopy, Speech, SpeechTherapy, SpinalCordInjury, Spine, SpiritualDirection, Sports,
    SportsCoachingSportsCoaching, SportsInjuries, SportsNutrition, SportsTraining, Spreadsheets, SQL, StaffDevelopment,
    StaffTraining, StageLighting, StageManagement, StakeholderManagement, StandardOperatingProcedureSOP, StarCCM,
    StartupConsulting, Startups, StartupVentures, StartupDevelopment, Stata, State, Statements, Stations,
    StatisticalDataAnalysis, Statistics, SteamBoilers, SteelMaking, Sterilization, StockManagement, StoreManagement,
    Stormwater, Storyboarding, Storytelling, StrategicAlliances, StrategicCommunications, StrategicConsulting,
    StrategicInitiatives, StrategicLeadership, StrategicNegotiations, StrategicPartnerships, StrategicPlanning,
    StrategicRoadmaps, StrategicSourcing, StrategicThinking, Strategies, Strategy, StrategyExecution, StreamingMedia,
    StrengthConditioning, StrengthTraining, StressAnalysis, StressManagement, StrokeRehabilitation, Structural,
    StructuralAnalysis, StructuralAnalysisEngineeringDesign, StructuralCalculations, StructuralEngineering, Structuring,
    Student, StudentAffairs, StudentDevelopment, StudentEngagement, Studio, StudioPhotography, Styling, Subcontracting,
    Subdivisions, SuccessfulBusinessOwner, SupervisorySkills, SupplierNegotiation, SupplyChain, SupplyManagement,
    Support, SupremeCourt, Surgery, SurgicalInstruments, Surveillance, SurveyDesign, Surveying, SurveyResearch,
    Sustainability, SustainableAgriculture, SustainableDesign, SustainableDevelopment, SustainableForestManagement,
    SwimInstruction, Swimming, SWOTanalysis, SyntheticBiology, System, SystemAdministration, Systems,
    SystemsEngineering, SystemsProducts, SystemsThinking, Tableau, Tactics, TalentManagement, TapDance, TargetCosting,
    Tax, TaxAccounting, TaxAccountingTax, Taxations, TaxCreditLIHTC, TaxLawTaxLaw, TaxPreparation, TaxTreaties,
    TeacherTraining, Teaching, TeachingEnglishasa, TeachingEnglishasaForeignLanguage, TeachingWriting, Team,
    TeamBuilding, TeamCoordination, TeamLeadership, TeamManagement, TeamMotivation, TeamOrganisation, Teams, TeamSpirit,
    Teamwork, Technical, TechnicalAnalysis, TechnicalCommunication, TechnicalLeadership, TechnicalRecruiting,
    TechnicalSupport, TechnicalSupportTroubleshooting, TechnicalTranslation, TechnicalWriting, Technologies,
    TechnologyHIT, TechnologyIntegration, TechnologyTransfer, TeethWhitening, TelecommunicationsTelecommunications,
    Telephony, TelevisionTelevision, TenaciousWorkEthic, Tennis, TensorFlow, Terminology, TestAutomation, TestCases,
    Testing, TestPlanning, TextEditing, Textiles, Theatre, TheatreActing, Theatrical, TherapeuticListening,
    TherapeuticMassage, TherapyCBT, TherapyManagementMTM, Thermodynamics, Thermoplastics, ThirdPartyLogistics3PL,
    ThoughtLeadership, TicketingSystems, Tiling, Timber, Time, Timeefficient, TimeManagement, TissueCulture,
    TitleSearches, Titration, TNCC, Topcon, Toxicology, TradeMarketing, TrademarkInfringement, Trademarks, TradeSecrets,
    TradeShows, Trading, Trados, Traffic, TrafficManagement, Training, TrainingDelivery, Transcribing, TransferPricing,
    Translation, Transportation, TransportationEngineering, TransportationManagement, TransportationPlanning,
    TraumaticBrainInjury, Travel, TravelManagement, TravelManagementTourism, TravelPhotography, TravelPlanning,
    TreatmentPlants, TreeClimbing, TreePlanting, Trees, TrendForecasting, TribonM3, Trimble, TruckDriving, Trucking,
    Tumor, Tunnels, Tutoring, TVProduction, Twitter, TypeScript, Typing, USDepartmentofDefense,
    USFederalCommunicationsCommissionFCC, USFoodandDrugAdministrationFDA, USGenerallyAcceptedAccountingPrinciplesGAAP,
    USHealthInsurancePortabilityandAccountabilityActHIPAA, USSECFilings, USSecuritiesandExchangeCommissionSEC, UAV,
    UiPath, UML, UndergroundMining, Underwater, Underwriting, UnifiedCommunications, UnifiedModelingLanguage,
    UnionRelations, UniversityTeaching, Unix, UnrealEngine4, UnsecuredLoans, Upstream, Urban, Urbanism, UrbanPlanning,
    UrbanPlanningUrbanDesign, Urinalysis, UrologyUrology, UsabilityTesting, UsercenteredDesign, UserAcceptanceTesting,
    UserExperienceDesignUED, UserExperienceUX, UserInterfaceDesign, UtilitiesEnergy, UV, UVVisSpectroscopy, VRay,
    Vaccinations, Validation, Valuation, ValueAddedTaxVAT, ValueEngineering, VariableDataPrinting, VariableFrequency,
    VarianceAnalysis, Vascular, VascularSurgery, VEGAS, VendorContracts, VendorManagement, VerbalDeescalation, Verilog,
    VesselOperations, Vessels, Veterans, VeterinaryMedicineVeterinaryMedicine, VeterinarySurgery, VHDL, Video,
    VideoGames, Videography, VideoPostProduction, VideoProcessing, VideoProduction, VideoVideoEditing, Virology,
    Virtualization, VirtualPrivate, Visio, VisualArts, VisualArtsPainting, Visualization, VisualMerchandising, VMware,
    VoiceAccent, VoiceoverIPVoIP, Volunteer, Volunteering, VolunteerManagement, VolunteerTraining, VotingRights,
    WalMart, Walking, Warehouse, WarehouseManagementSystems, Washing, Waste, WasteManagement, WasteWater, Watches,
    Watercolor, WaterEngineering, WaterPumps, WaterResource, WaterResourceManagement, WaterSupply, WaterTreatment,
    Wealth, WeaponsHandling, WebContentWriting, WebDesign, WebDevelopment, WebDevelopmentJavaScript, WebEditing,
    WebHostingWebHosting, WebServices, WeddingPhotography, Weddings, WeightGain, WeightTraining, Welding,
    WeldingInspection, WellnessCoaching, WellnessWellness, WesternBlotting, WholesaleOperations, WholesaleWholesale,
    WideFormatPrinting, WildlifeBiology, WildlifeRehabilitation, Wills, WindowCleaning, Windows, Windows7,
    WindowsServer, Wine, WineSales, Wireframing, WirelessTechnologies, Wood, Woodworking, WordPress, Workingwith,
    WorkingwithAdolescents, WorkingWithChildren, WorkingwithFirstTimeHomeBuyers, WorkingwithSurgeons,
    WorkingwithTenants, WorkplaceSafety, WorldHistory, Writing, WritingWriting, Written, Xray, XBRL, Xero, XML,
    Yachting, Yardi, YardiVoyager, Yarn, YieldManagement, Yoga, Youth, YouthLeadership, YouthMentoring, YouthMinistry,
    YouthPrograms, YouthWork, YouTube, Zoning, Zoology, ZoologyAnimalBehavior,

}
